### PR TITLE
Fix word wrap bug #24

### PR DESCRIPTION
**Pull request by mattlorimor**
This PR should fix the word wrap bug outlined in #24.

### CODE REVIEW

**Comment by mattlorimor** [comment]
When you get a chance, can you take a peek at this, @mattfarina?

**Comment by matthewlorimor-wf** [comment]
Or perhaps @technosophos?

**Comment by mattlorimor** [comment]
Or perhaps @technosophos?

**Comment by technosophos** [comment]
This looks great. @mattfarina Should we do a new release of goutils? This is a pretty significant bugfix.

**Pull request merged**
